export enum ResourceName {
    APPSERVICE,
    APPSERVICEPLAN,
    RESOURCEGROUP,
    SQLSERVER,
    STORAGEACCOUNT,
}
export enum ResourceType {
    APPSERVICE,
    APPSERVICEPLAN,
    STORAGEACCOUNT,
}